### ISSUE TITLE
Weird Trim Shenanigans

### ISSUE THREAD

**Issue by Tri-Iris** [mrmelon54/armored_elytra#15] opened 2024-02-19 20:40 UTC
This is on 1.0.6 and Trims act weird. They're outside of the chest plate model and can be seen in f5 mode. 

![2024-02-19_12 34 12](https://github.com/mrmelon54/armored_elytra/assets/143235935/f58ecc8b-53ae-48e9-82d7-c43e6b8884da)
![2024-02-19_12 37 10](https://github.com/mrmelon54/armored_elytra/assets/143235935/75257f4e-a99e-4aa5-9bb6-9e0195eadcb4)

**Comment by mrmelon54** [comment] 2024-02-19 20:47
What mods are you playing with?

**Comment by Tri-Iris** [comment] 2024-02-19 20:54
Architectury API
Armor Poser
Ash APO
Axiom
Back-burner
Beenfo
Better Advancements
Better Clouds
Better End Sky
Boat Iten View
Carpet
Carpet-Fixes
Cloth Config API
Clumps
Collective
Comforts
Continuity
Coord Finder
Dynamic FPS
Ears
Elytra Trims
Entity Culling
Fabric API
Fabric Language Kotlin
FerriteCore
Flourish
Forge Config API Port
Freecam
ImmediatelyFast
Indium
Iris Shaders
LazyDFU
Lithium
Map Tooltip
Mod Menu
Mouse Tweaks
Nullscape
Shoulder Surfing Reloaded
Shulker Box Tooltip
Sodium
Sodium Extra
Tax Free Levels
Traverse
True Ending: Ender Dragon Overhaul
Universal Graves
View Distance Fix
YetAnotherConfigLib
Zoomify

**Comment by mrmelon54** [comment] 2024-02-19 21:03
Duplicate of #1

**Closed** 2024-02-19 21:04 UTC
